server:
  port: 8080
  servlet:
    context-path: /api

spring:
  # 分库分表配置
  shardingsphere:
    datasource:
      names: xin_picture
      xin_picture:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/xin_picture
        username: root
        password: root
    rules:
      sharding:
        tables:
          picture:
            actual-data-nodes: yu_picture.picture  # 动态分表
            table-strategy:
              standard:
                sharding-column: spaceId
                sharding-algorithm-name: picture_sharding_algorithm  # 使用自定义分片算法
        sharding-algorithms:
          picture_sharding_algorithm:
            type: CLASS_BASED
            props:
              strategy: standard
              algorithmClassName: com.xin.xinpicturebackend.manager.sharding.PictureShardingAlgorithm
    props:
      sql-show: true  #测试环境开启，打印执行的sql
  # Redis 配置
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 5000
  application:
    name: xin-picture-backend
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xin_picture
    username: root
    password: root
  #图片上传大小限制
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
mybatis-plus:
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: false
    # 仅在开发环境，显示执行的sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDeleted # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值
#阿里云对象存储，替换其中的密钥
#cos:
#  client:
#    accessKey: xxx
#    secretKey: xxx
#    region: xxx
#    bucket: xxx
#    endpoint: xxx
#    host: xxx

# 阿里云百炼AI配置
#aliYunAi:
#  apiKey: xxx

#接口文档配置
knife4j:
  enable: true
  openapi:
    title: xin-picture接口文档
    version: v1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.xin.xinpicturebackend.controller